version: "3"

services:

  mysql-database-service:
    image: mysql
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: user_auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks: [ ride-booking-app-network ]

  mongodb-database-service:
    image: mongo
    container_name: mongodb-database-container
    ports:
      - "27018:27017"
    networks: [ ride-booking-app-network ]

  user-auth-service:
    build: user-auth/
    container_name: user-auth-service-container
    ports:
      - "8081:8081"
    networks: [ ride-booking-app-network ]
    depends_on: [ mysql-database-service, eureka-server-service ]
    restart: always

  booking-app-service:
    build: booking-app/
    container_name: booking-app-service-container
    ports:
      - "8082:8082"
    networks: [ ride-booking-app-network ]
    depends_on: [ mongodb-database-service, eureka-server-service ]
    restart: always

  api-gateway-service:
    build: api-gateway/
    container_name: api-gateway-service-container
    ports:
      - "9000:9000"
    networks: [ ride-booking-app-network ]
    depends_on: [ user-auth-service, booking-app-service, eureka-server-service ]
    restart: always

  eureka-server-service:
    build: eureka-server/
    container_name: eureka-server-service-container
    networks: [ ride-booking-app-network ]
    ports:
      - "8761:8761"
    restart: always

networks:
  ride-booking-app-network:
    driver: bridge