server:
  port: 9000
  error:
    include-message: always

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
  instance:
    prefer-ip-address: false